### ISSUE TITLE
Replaced placeholder text and images

### ISSUE THREAD

**Issue by AshtmlB** [kmiddlesworth/winterim-ab-log#9]
@kmiddlesworth 
Hey Mr. Middlesworth! I replaced all the placeholder bacon with relevant images. Also, all of the text for each day I replaced with my log. How should I push these changes? Thanks

**Comment by kmiddlesworth** [comment]
Hi Asher! 

Ok. All you need to do now is make sure you merge your commits into the `main` branch. 

It looks like you haven't pushed your changes yet. As soon as you do that, your site should be updated within about 1 to 2 mins. 

Does this make sesne?
